server {
	listen 80;

	root /app;

	location /img {
	    alias /app/public/img;
		try_files $uri =404;
		expires 1y;
		access_log off;
		add_header Cache-Control "public";
	}

	location / {
		client_max_body_size 16M;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_pass http://beit-yehoshua-container:3000;
	}

# 	location / {
# 		try_files $uri $uri/ /index.html;
# 	}
}
