'use client'
// import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import Header from '@/components/Header'
import { SessionProvider } from 'next-auth/react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className="box-border list-none decoration-0">
            <SessionProvider>
               <Header/>
               {children}
            </SessionProvider>
         </body>
      </html>
   )
}
