'use client'
// import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import Header from '@/components/Header'
import Navigation from '@/components/Navigation'
import { SessionProvider } from 'next-auth/react'
// import {ClerkProvider} from "@clerk/nextjs"

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// }

// export default function RootLayout({ children, session, ...pageProps  }: { children: React.ReactNode }) {
// export default function RootLayout({ children, pageProps: { session, ...pageProps } }){
export default function RootLayout({ children, session, ...pageProps }) {

   return (
       // <ClerkProvider>
      <html lang="en">
         <body className="box-border list-none decoration-0">
            <SessionProvider
               session={session} {...pageProps}
            >
               <Navigation/>
               {/*<Header/>*/}
               {children}
            </SessionProvider>
         </body>
      </html>
       // </ClerkProvider>
   )
}
